
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const isRTL = language === 'ar';

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const translations = {
    en: {
      // Navigation & Header
      'learnhub': 'LearnHub',
      'courses': 'Courses',
      'about': 'About Us',
      'contact': 'Contact Us',
      'dashboard': 'Dashboard',
      'login': 'Login',
      'signup': 'Sign Up',
      'logout': 'Log out',
      'profile': 'Profile',
      'account': 'Account Settings',
      
      // User Roles
      'student': 'Student',
      'teacher': 'Instructor',
      'admin': 'Administrator',
      'switch_to_student': 'Switch to Student',
      'switch_to_teacher': 'Switch to Instructor',
      'switch_to_admin': 'Switch to Admin',
      
      // Admin Dashboard
      'admin_dashboard': 'Admin Dashboard',
      'manage_platform': 'Manage your platform and monitor performance',
      'overview': 'Overview',
      'user_management': 'User Management',
      'analytics': 'Analytics',
      'revenue_control': 'Revenue Control',
      'total_students': 'Total Students',
      'total_teachers': 'Total Teachers',
      'total_revenue': 'Total Revenue',
      'active_courses': 'Active Courses',
      'from_last_month': 'from last month',
      
      // Quick Actions
      'quick_actions': 'Quick Actions',
      'manage_users': 'Manage Users',
      'manage_users_desc': 'Add, edit, or remove students and teachers',
      'view_analytics': 'View Analytics',
      'view_analytics_desc': 'Monitor platform performance and engagement',
      'revenue_settings': 'Revenue Settings',
      'revenue_settings_desc': 'Control course pricing and revenue distribution',
      
      // Recent Activity
      'recent_activity': 'Recent Activity',
      'new_teacher_registered': 'New teacher registered',
      'sarah_johnson_joined': 'Sarah Johnson joined',
      'course_published': 'Course published',
      'advanced_react_dev': 'Advanced React Development',
      'payment_processed': 'Payment processed',
      'course_enrollment': '$299 course enrollment',
      
      // User Management
      'students': 'Students',
      'teachers': 'Teachers',
      'admins': 'Admins',
      'add_user': 'Add User',
      'add_new_user': 'Add New User',
      'name': 'Name',
      'email': 'Email',
      'role': 'Role',
      'status': 'Status',
      'stats': 'Stats',
      'actions': 'Actions',
      'search_users': 'Search users...',
      'all_roles': 'All Roles',
      'active': 'active',
      'inactive': 'inactive',
      'courses_enrolled': 'courses enrolled',
      'courses_taught': 'courses',
      'students_count': 'students',
      'cancel': 'Cancel',
      'enter_user_name': 'Enter user name',
      'enter_email': 'Enter email address',
      'select_role': 'Select role',
      
      // Time stamps
      'hours_ago': 'h ago',
      'ago': 'ago',

      // About Page
      'our_story': 'Our Story',
      'our_story_desc': 'LearnHub was founded with a simple mission: to make quality education accessible to everyone, \n everywhere. We believe that learning should be flexible, engaging, and tailored to individual needs.',
      'our_vision': 'Our Vision',
      'our_vision_desc': "We envision a world where anyone can learn anything, anytime, anywhere. Our platform \n connects learners with expert instructors, providing personalized learning experiences \n that adapt to your pace and style.",
      'our_impact_desc': "Since our founding, we've helped over 500,000 students achieve their learning goals \n through our comprehensive course catalog and supportive community.",
      'our_values': 'Our Values',
      'community_first': 'Community First',
      'community_first_desc': 'We believe in the power of learning together and supporting each other.',
      'goal_oriented': 'Goal Oriented',
      'goal_oriented_desc': 'Every course is designed to help you achieve your specific learning objectives.',
      'excellence': 'Excellence',
      'excellence_desc': 'We maintain the highest standards in content quality and learning experience.',
      'passion': 'Passion',
      'passion_desc': 'We are passionate about education and helping people unlock their potential.',
      'meet_our_team': 'Meet Our Team',
      'ceo_founder': 'CEO & Founder',
      'cto': 'CTO',
      'head_of_education': 'Head of Education',
      'lead_developer': 'Lead Developer',

      // Account Page
      'manage_account_desc': 'Manage your account security and preferences',
      'security': 'Security',
      'change_password': 'Change Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'update_password': 'Update Password',
      'two_factor_auth': 'Two-Factor Authentication',
      'sms_auth': 'SMS Authentication',
      'sms_auth_desc': 'Receive codes via SMS',
      'notifications': 'Notifications',
      'email_notifications': 'Email Notifications',
      'email_notifications_desc': 'Receive notifications via email',
      'push_notifications': 'Push Notifications',
      'push_notifications_desc': 'Receive push notifications',
      'marketing_emails': 'Marketing Emails',
      'marketing_emails_desc': 'Receive promotional content',
      'course_updates': 'Course Updates',
      'course_updates_desc': 'Updates about your enrolled courses',
      'privacy_settings': 'Privacy Settings',
      'public_profile': 'Public Profile',
      'public_profile_desc': 'Make your profile visible to others',
      'show_learning_progress': 'Show Learning Progress',
      'show_learning_progress_desc': 'Display your course progress publicly',
      'show_certificates': 'Show Certificates',
      'show_certificates_desc': 'Display earned certificates on profile',
      'billing_payments': 'Billing & Payments',
      'payment_methods': 'Payment Methods',
      'payment_methods_desc': 'Manage your payment methods',
      'manage': 'Manage',
      'billing_history': 'Billing History',
      'billing_history_desc': 'View your purchase history',
      'view_history': 'View History',
      'danger_zone': 'Danger Zone',
      'delete_account': 'Delete Account',
      'delete_account_desc': 'Permanently delete your account and all data',
      'passwords_do_not_match': 'Passwords do not match',
      'confirm_delete_account': 'Are you sure you want to delete your account? This action cannot be undone.',

      // Contact Page
      'contact_us_desc': "Have questions? We'd love to hear from you.",
      'send_us_message': 'Send us a message',
      'name_required': 'Name *',
      'email_required': 'Email *',
      'subject_required': 'Subject *',
      'message_required': 'Message *',
      'sending': 'Sending...',
      'send_message': 'Send Message',
      'get_in_touch': 'Get in Touch',
      'get_in_touch_desc': "We're here to help! Reach out to us through any of the following channels, \n and we'll get back to you as soon as possible.",
      'support_email_address': 'support@learnhub.com',
      'phone_number': '+1 (555) 123-4567',
      'address_details': '123 Learning Street, Education City, EC 12345',
      'hours_details': 'Mon-Fri: 9AM-6PM PST',
      'faq': 'Frequently Asked Questions',
      'faq_desc': 'Check out our FAQ section for quick answers to common questions \n about courses, payments, and technical support.',
      'message_sent_title': 'Message Sent!',
      'message_sent_desc': "Thank you for contacting us. We'll get back to you soon.",

      // Course Details Page
      'course_introduction': 'Course Introduction',
      'students_count_details': 'students',
      'created_by': 'Created by',
      'last_updated': 'Last updated',
      'what_you_will_learn': "What you'll learn",
      'requirements': 'Requirements',
      'course_curriculum': 'Course Curriculum',
      'sections': 'sections',
      'lectures': 'lectures',
      'total_length': 'total length',
      'preview': 'Preview',
      'instructor_role': 'Senior Full Stack Developer & Instructor',
      'instructor_rating': 'Instructor Rating',
      'instructor_bio': "John is a seasoned developer with over 10 years of experience in web development. \n He has worked with major tech companies and has taught thousands of students worldwide.",
      'reviews_placeholder': 'Reviews will be displayed here',
      'discount_badge': '50% OFF',
      'price_countdown': '2 days left at this price!',
      'enroll_now': 'Enroll Now',
      'add_to_wishlist': 'Add to Wishlist',
      'money_back_guarantee': '30-Day Money-Back Guarantee',
      'full_lifetime_access': 'Full Lifetime Access',
      'access_on_mobile_tv': 'Access on Mobile and TV',
      'certificate_of_completion': 'Certificate of Completion',

      // Course Management Page
      'course_management_title': 'Course Management',
      'course_management_desc': 'Create and manage your courses',
      'create_course': 'Create Course',
      'create_new_course': 'Create New Course',
      'course_title': 'Course Title',
      'enter_course_title': 'Enter course title',
      'description': 'Description',
      'course_description': 'Course description',
      'price_usd': 'Price ($)',
      'duration': 'Duration',
      'duration_placeholder': 'e.g., 40 hours',
      'category': 'Category',
      'select_category': 'Select category',
      'web_development': 'Web Development',
      'data_science': 'Data Science',
      'mobile_development': 'Mobile Development',
      'design': 'Design',
      'level': 'Level',
      'select_level': 'Select level',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'price': 'Price',
      'enrollments': 'Enrollments',
      'revenue': 'Revenue',
      'course_created_toast_title': 'Course Created',
      'course_created_toast_desc': 'Your new course has been created successfully.',
      'course_deleted_toast_title': 'Course Deleted',
      'course_deleted_toast_desc': 'The course has been removed from your catalog.',

      // Courses Page
      'explore_courses': 'Explore Courses',
      'search_courses_instructors': 'Search courses or instructors...',
      'filters': 'Filters',
      'categories': 'Categories',
      'free': 'Free',
      'paid': 'Paid',
      'clear_filters': 'Clear Filters',
      'courses_found': 'courses found',
      'no_courses_found': 'No courses found',
      'try_adjusting_filters': 'Try adjusting your search or filter criteria',
      'marketing': 'Marketing',
      'business': 'Business',

      // Dashboard Page
      'welcome_back': 'Welcome back, {userName}!',
      'learning_journey_prompt': 'Ready to continue your learning journey?',
      'your_progress': 'Your Progress',
      'courses_enrolled_dashboard': 'Courses Enrolled',
      'average_progress': 'Average Progress',
      'total_learning_time': 'Total Learning Time',
      'my_courses': 'My Courses',
      'by_instructor': 'by {instructor}',
      'progress': 'Progress',
      'lessons_count': 'lessons',
      'next_lesson_prompt': 'Next: {nextLesson}',
      'continue_learning': 'Continue',
      'browse_courses': 'Browse Courses',
      'edit_profile': 'Edit Profile',
      'achievements': 'Achievements',
      'first_course_completed_achievement': 'First Course Completed',
      'week_streak_achievement': 'Week Streak',
      'fast_learner_achievement': 'Fast Learner',
      'earned_badge': 'Earned',

      // Login Page
      'login_successful_modal_title': 'Login Successful',
      'login_failed_modal_title': 'Login Failed',
      'login_successful_modal_desc': 'Welcome back! You have been successfully logged in.',
      'login_failed_modal_desc': 'Invalid email or password. Please try again.',

      // Not Found Page
      'not_found_title': '404',
      'not_found_message': 'Oops! Page not found',
      'return_to_home': 'Return to Home',

      // Payment Page
      'complete_your_purchase': 'Complete Your Purchase',
      'secure_checkout_desc': 'Secure checkout powered by industry-standard encryption',
      'payment_information': 'Payment Information',
      'payment_method': 'Payment Method',
      'credit_debit_card': 'Credit/Debit Card',
      'paypal_coming_soon': 'PayPal (Coming Soon)',
      'card_number': 'Card Number',
      'expiry_date': 'Expiry Date',
      'cvv': 'CVV',
      'cardholder_name': 'Cardholder Name',
      'billing_address': 'Billing Address',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'city': 'City',
      'state': 'State',
      'zip_code': 'ZIP Code',
      'processing': 'Processing...',
      'pay_amount': 'Pay ${course.price}',
      'order_summary': 'Order Summary',
      'course_price': 'Course Price:',
      'discount_label': 'Discount:',
      'total_label': 'Total:',
      'secure_encryption_desc': 'Secure 256-bit SSL encryption',

      // Payment Analytics Page
      'payment_analytics_title': 'Payment Analytics',
      'payment_analytics_desc': 'Track your revenue and payment performance',
      'filter_button': 'Filter',
      'export_button': 'Export',
      'last_30_days': 'Last 30 days',
      'monthly_growth': 'Monthly Growth',
      'compared_to_last_month': 'Compared to last month',
      'total_transactions': 'Total Transactions',
      'this_month': 'This month',
      'average_order_value': 'Average Order Value',
      'per_transaction': 'Per transaction',
      'recent_payments': 'Recent Payments',
      'subscriptions': 'Subscriptions',
      'active_subscriptions': 'Active Subscriptions',
      'next_billing_date': 'Next billing: {nextBilling}',
      'amount_per_month': '${amount}/month',

      // Payment Success Page
      'payment_successful_title': 'Payment Successful!',
      'payment_successful_desc': 'Thank you for your purchase. You now have access to your course.',
      'course_enrolled_label': 'Course Enrolled:',
      'go_to_dashboard_button': 'Go to Dashboard',
      'browse_more_courses_button': 'Browse More Courses',
      'confirmation_email_sent': 'A confirmation email has been sent to your registered email address.',

      // Profile Page
      'manage_profile_desc': 'Manage your personal information and public profile',
      'profile_picture': 'Profile Picture',
      'change_picture': 'Change Picture',
      'personal_information': 'Personal Information',
      'edit_button': 'Edit',
      'bio': 'Bio',
      'website': 'Website',
      'linkedin': 'LinkedIn',
      'twitter': 'Twitter',
      'save_changes_button': 'Save Changes',

      // Promo Code Management Page
      'promo_code_management_title': 'Promo Code Management',
      'promo_code_management_desc': 'Create and manage discount codes for your courses',
      'create_promo_code_button': 'Create Promo Code',
      'create_new_promo_code_title': 'Create New Promo Code',
      'promo_code_label': 'Promo Code',
      'enter_or_generate_code': 'Enter code or generate',
      'generate_button': 'Generate',
      'promo_code_desc_label': 'Promo code description',
      'discount_type_label': 'Discount Type',
      'percentage_option': 'Percentage',
      'fixed_amount_option': 'Fixed Amount',
      'percentage_input_label': 'Percentage (%)',
      'amount_input_label': 'Amount ($)',
      'usage_limit_label': 'Usage Limit',
      'applicable_courses_label': 'Applicable Courses',
      'all_courses_option': 'All Courses',
      'discount_column': 'Discount',
      'usage_column': 'Usage',
      'expires_column': 'Expires',
      'all_option': 'All',
      'promo_code_created_toast_title': 'Promo Code Created',
      'promo_code_created_toast_desc': 'Your new promo code has been created successfully.',
      'promo_code_deleted_toast_title': 'Promo Code Deleted',
      'promo_code_deleted_toast_desc': 'The promo code has been removed.',
      'code_copied_toast_title': 'Code Copied',
      'code_copied_toast_desc': 'Promo code "{code}" copied to clipboard.',

      // Quiz Management Page
      'quiz_management_title': 'Quiz Management',
      'quiz_management_desc': 'Create and manage course quizzes',
      'create_quiz_button': 'Create Quiz',
      'create_new_quiz_title': 'Create New Quiz',
      'quiz_title_label': 'Quiz Title',
      'enter_quiz_title': 'Enter quiz title',
      'duration_minutes_label': 'Duration (minutes)',
      'quiz_desc_label': 'Quiz description',
      'associated_lesson_label': 'Associated Lesson',
      'lesson_name_placeholder': 'Lesson name',
      'questions_label': 'Questions',
      'add_question_button': 'Add Question',
      'question_label': 'Question {index + 1}',
      'enter_question_placeholder': 'Enter your question',
      'option_label': 'Option {optionIndex + 1}',
      'correct_answer_label': 'Correct Answer',
      'option_1': 'Option 1',
      'option_2': 'Option 2',
      'option_3': 'Option 3',
      'option_4': 'Option 4',
      'lesson_prefix': 'Lesson: {lesson}',
      'attempts_label': 'Attempts',
      'avg_score_label': 'Avg Score',
      'quiz_created_toast_title': 'Quiz Created',
      'quiz_created_toast_desc': 'Your new quiz has been created successfully.',
      'quiz_deleted_toast_title': 'Quiz Deleted',
      'quiz_deleted_toast_desc': 'The quiz has been removed.',

      // Signup Page
      'create_account_title': 'Create Account',
      'join_community_desc': 'Join our learning community',
      'signup_with_gmail_button': 'Sign up with Gmail',
      'or_continue_with': 'Or continue with',
      'i_want_to_label': 'I want to',
      'learn_as_student_option': 'Learn as a Student',
      'teach_as_instructor_option': 'Teach as an Instructor',
      'password_label': 'Password',
      'creating_account_button': 'Creating Account...',
      'already_have_account_prompt': 'Already have an account? ',
      'sign_in_link': 'Sign in',

      // Teacher Dashboard Page
      'instructor_dashboard_title': 'Instructor Dashboard',
      'instructor_dashboard_desc': 'Manage your courses and track performance',
      'quizzes_nav': 'Quizzes',
      'manage_quizzes_nav_desc': 'Create and manage quizzes',
      'track_payments_nav_desc': 'Track payments & revenue',
      'promo_codes_nav': 'Promo Codes',
      'manage_promo_codes_nav_desc': 'Manage discount codes',
      'total_courses_stats': 'Total Courses',
      'avg_rating_stats': 'Avg. Rating',
      'payments_tab': 'Payments',
      'promos_tab': 'Promo Codes',
      'add_course_button': 'Add Course',
      'course_title_required_label': 'Course Title *',
      'price_required_label': 'Price *',
      'programming_option': 'Programming',
      'students_stats_prefix': 'Students: {students}',
      'revenue_stats_prefix': 'Revenue: ${revenue}',
      'price_stats_prefix': 'Price: ${price}',
      'rating_stats_prefix': 'Rating: {rating}/5',
      'no_ratings_label': 'No ratings',
      'view_button': 'View',
      'remove_button': 'Remove',
      'payment_history_title': 'Payment History',
      'student_column': 'Student',
      'course_column': 'Course',
      'amount_column': 'Amount',
      'date_column': 'Date',
      'status_column': 'Status',
      'create_promo_button': 'Create Promo',
      'promo_code_required_label': 'Promo Code *',
      'discount_required_label': 'Discount *',
      'select_type_placeholder': 'Select type',
      'percentage_discount_option': 'Percentage (%)',
      'fixed_amount_discount_option': 'Fixed Amount ($)',
      'max_uses_label': 'Max Uses',
      'code_column': 'Code',
      'discount_value_suffix': '{discount}{type} off',
      'error_toast_title': 'Error',
      'fill_required_fields_toast_desc': 'Please fill in all required fields',
      'success_toast_title': 'Success',
      'course_created_successfully_toast_desc': 'Course created successfully',
      'course_removed_successfully_toast_desc': 'Course removed successfully',
      'promo_code_created_successfully_toast_desc': 'Promo code created successfully',

      // Course Card Component
      'view_details_button': 'View Details',

      // Courses Preview Component
      'featured_courses_title': 'Featured Courses',
      'featured_courses_desc': 'Discover our most popular courses and start your learning journey today',
      'view_all_courses_button': 'View All Courses',

      // Feature Section Component
      'why_choose_platform_title': 'Why Choose Our Platform?',
      'why_choose_platform_desc': 'Discover the features that make learning effective, engaging, and accessible for everyone.',
      'expert_instructors_feature_title': 'Expert Instructors',
      'expert_instructors_feature_desc': 'Learn from industry professionals and certified experts who bring real-world experience to every lesson.',
      'flexible_learning_feature_title': 'Flexible Learning',
      'flexible_learning_feature_desc': 'Study at your own pace with 24/7 access to course materials. Perfect for busy schedules and different learning styles.',
      'interactive_content_feature_title': 'Interactive Content',
      'interactive_content_feature_desc': 'Engage with hands-on projects, quizzes, and community discussions to enhance your learning experience.',
      'comprehensive_curriculum_feature_title': 'Comprehensive Curriculum',
      'comprehensive_curriculum_feature_desc': 'Access structured learning paths designed to take you from beginner to expert in your chosen field.',
      'certificates_recognition_feature_title': 'Certificates & Recognition',
      'certificates_recognition_feature_desc': 'Earn verified certificates upon completion to showcase your skills to employers and advance your career.',
      'support_24_7_feature_title': '24/7 Support',
      'support_24_7_feature_desc': 'Get help whenever you need it with our dedicated support team and active community forums.',

      // Hero Section Component
      'hero_title': 'Learn Anything, Anytime',
      'hero_subtitle': 'Your journey to knowledge starts here. Access thousands of courses from expert instructors and learn at your own pace.',
      'watch_demo_button': 'Watch Demo',
      'courses_available_stats': 'Courses Available',
      'students_enrolled_stats': 'Students Enrolled',
      'expert_instructors_stats': 'Expert Instructors',
      'promo_video_title': 'LearnHub Promotional Video',

      // Login Form Component
      'welcome_back_title': 'Welcome Back',
      'sign_in_to_account_desc': 'Sign in to your account',
      'continue_with_gmail_button': 'Continue with Gmail',
      'enter_your_email_placeholder': 'Enter your email',
      'enter_your_password_placeholder': 'Enter your password',
      'forgot_password_link': 'Forgot password?',
      'signing_in_button': 'Signing in...',
      'sign_in_button': 'Sign In',
      'dont_have_account_prompt': "Don't have an account? ",
      'sign_up_link': 'Sign up',

      // Modal Component
      'ok_button': 'OK',

      // Video Player Component
      'sample_video_badge': 'SAMPLE',

      // Admin Analytics Dashboard Component
      'total_users_stats': 'Total Users',
      'plus_15_percent_from_last_month': '+15% from last month',
      'course_completions_stats': 'Course Completions',
      'plus_8_percent_from_last_month': '+8% from last month',
      'avg_session_time_stats': 'Avg. Session Time',
      'plus_5_percent_from_last_month': '+5% from last month',
      'platform_rating_stats': 'Platform Rating',
      'plus_0_2_from_last_month': '+0.2 from last month',
      'user_growth_chart_title': 'User Growth',
      'revenue_trend_chart_title': 'Revenue Trend',
      'course_completion_status_chart_title': 'Course Completion Status',
      'top_performing_courses_chart_title': 'Top Performing Courses',
      'platform_performance_summary_title': 'Platform Performance Summary',
      'student_engagement_section_title': 'Student Engagement',
      'daily_active_users_label': 'Daily Active Users:',
      'weekly_active_users_label': 'Weekly Active Users:',
      'monthly_active_users_label': 'Monthly Active Users:',
      'teacher_performance_section_title': 'Teacher Performance',
      'avg_course_rating_label': 'Avg. Course Rating:',
      'course_completion_rate_label': 'Course Completion Rate:',
      'student_satisfaction_label': 'Student Satisfaction:',
      'revenue_metrics_section_title': 'Revenue Metrics',
      'monthly_revenue_label': 'Monthly Revenue:',
      'avg_course_price_label': 'Avg. Course Price:',
      'revenue_growth_label': 'Revenue Growth:',
      'plus_23_percent': '+23%',

      // Admin Platform Settings Component
      'platform_settings_title': 'Platform Settings',
      'general_settings_section_title': 'General Settings',
      'platform_name_label': 'Platform Name',
      'support_email_label': 'Support Email',
      'welcome_message_label': 'Welcome Message',
      'user_registration_section_title': 'User Registration',
      'enable_user_registration_label': 'Enable User Registration',
      'enable_user_registration_desc': 'Allow new users to register on the platform',
      'require_email_verification_label': 'Require Email Verification',
      'require_email_verification_desc': 'Users must verify their email before accessing the platform',
      'allow_guest_access_label': 'Allow Guest Access',
      'allow_guest_access_desc': 'Allow users to browse courses without registration',
      'system_settings_section_title': 'System Settings',
      'max_file_upload_size_label': 'Max File Upload Size (MB)',
      'session_timeout_label': 'Session Timeout (minutes)',
      'maintenance_mode_label': 'Maintenance Mode',
      'maintenance_mode_desc': 'Enable maintenance mode to prevent user access',
      'max_courses_per_teacher_label': 'Max Courses Per Teacher',
      'course_approval_required_label': 'Course Approval Required',
      'course_approval_required_desc': 'New courses require admin approval before publishing',
      'save_all_settings_button': 'Save All Settings',
      'system_status_title': 'System Status',
      'online_status': 'Online',
      'server_status_label': 'Server Status',
      'uptime_label': 'Uptime',
      'avg_response_time_label': 'Avg Response Time',

      // Admin Revenue Control Component
      'platform_revenue_stats': 'Platform Revenue',
      'percent_of_total_label': '% of total',
      'teacher_revenue_stats': 'Teacher Revenue',
      'global_revenue_settings_title': 'Global Revenue Settings',
      'platform_fee_percentage_label': 'Platform Fee (%)',
      'platform_fee_percentage_desc': 'Percentage of course revenue that goes to the platform',
      'teacher_share_percentage_label': 'Teacher Share (%)',
      'teacher_share_percentage_desc': 'Percentage of course revenue that goes to teachers',
      'auto_approve_course_pricing_label': 'Auto-approve Course Pricing',
      'auto_approve_course_pricing_desc': 'Automatically approve teacher course pricing changes',
      'update_global_settings_button': 'Update Global Settings',
      'course_revenue_management_title': 'Course Revenue Management',
      'teacher_share_column': 'Teacher Share',
      'platform_fee_column': 'Platform Fee',
      'pricing_insights_title': 'Pricing Insights',
      'avg_course_price_stats': 'Average Course Price:',
      'highest_priced_course_stats': 'Highest Priced Course:',
      'lowest_priced_course_stats': 'Lowest Priced Course:',
      'courses_pending_approval_stats': 'Courses Pending Approval:',
      'revenue_distribution_title': 'Revenue Distribution',

    },
    ar: {
      // Navigation & Header
      'learnhub': 'منصة التعلم',
      'courses': 'الدورات',
      'about': 'من نحن',
      'contact': 'اتصل بنا',
      'dashboard': 'لوحة التحكم',
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'logout': 'تسجيل الخروج',
      'profile': 'الملف الشخصي',
      'account': 'إعدادات الحساب',
      
      // User Roles
      'student': 'طالب',
      'teacher': 'مدرس',
      'admin': 'مدير',
      'switch_to_student': 'التبديل إلى طالب',
      'switch_to_teacher': 'التبديل إلى مدرس',
      'switch_to_admin': 'التبديل إلى مدير',
      
      // Admin Dashboard
      'admin_dashboard': 'لوحة تحكم المدير',
      'manage_platform': 'إدارة منصتك ومراقبة الأداء',
      'overview': 'نظرة عامة',
      'user_management': 'إدارة المستخدمين',
      'analytics': 'التحليلات',
      'revenue_control': 'إدارة الإيرادات',
      'total_students': 'إجمالي الطلاب',
      'total_teachers': 'إجمالي المدرسين',
      'total_revenue': 'إجمالي الإيرادات',
      'active_courses': 'الدورات النشطة',
      'from_last_month': 'من الشهر الماضي',
      
      // Quick Actions
      'quick_actions': 'إجراءات سريعة',
      'manage_users': 'إدارة المستخدمين',
      'manage_users_desc': 'إضافة أو تعديل أو حذف الطلاب والمدرسين',
      'view_analytics': 'عرض التحليلات',
      'view_analytics_desc': 'مراقبة أداء المنصة والمشاركة',
      'revenue_settings': 'إعدادات الإيرادات',
      'revenue_settings_desc': 'التحكم في أسعار الدورات وتوزيع الإيرادات',
      
      // Recent Activity
      'recent_activity': 'النشاط الأخير',
      'new_teacher_registered': 'مدرس جديد مسجل',
      'sarah_johnson_joined': 'سارة جونسون انضمت',
      'course_published': 'دورة منشورة',
      'advanced_react_dev': 'تطوير React المتقدم',
      'payment_processed': 'تم معالجة الدفع',
      'course_enrollment': 'تسجيل دورة بـ 299 دولار',
      
      // User Management
      'students': 'الطلاب',
      'teachers': 'المدرسين',
      'admins': 'المديرين',
      'add_user': 'إضافة مستخدم',
      'add_new_user': 'إضافة مستخدم جديد',
      'name': 'الاسم',
      'email': 'البريد الإلكتروني',
      'role': 'الدور',
      'status': 'الحالة',
      'stats': 'الإحصائيات',
      'actions': 'الإجراءات',
      'search_users': 'البحث عن المستخدمين...',
      'all_roles': 'جميع الأدوار',
      'active': 'نشط',
      'inactive': 'غير نشط',
      'courses_enrolled': 'دورات مسجلة',
      'courses_taught': 'دورات',
      'students_count': 'طلاب',
      'cancel': 'إلغاء',
      'enter_user_name': 'أدخل اسم المستخدم',
      'enter_email': 'أدخل عنوان البريد الإلكتروني',
      'select_role': 'اختر الدور',
      
      // Time stamps
      'hours_ago': 'س مضت',
      'ago': 'مضت',

      // About Page
      'our_story': 'قصتنا',
      'our_story_desc': 'تأسست منصة التعلم بهدف بسيط: جعل التعليم الجيد متاحًا للجميع في كل مكان. نؤمن بأن التعلم يجب أن يكون مرنًا وجذابًا ومصممًا حسب الاحتياجات الفردية.',
      'our_vision': 'رؤيتنا',
      'our_vision_desc': 'نتصور عالمًا يمكن لأي شخص فيه تعلم أي شيء في أي وقت وفي أي مكان. منصتنا تربط المتعلمين بالمدربين الخبراء، وتوفر تجارب تعلم شخصية تتكيف مع وتيرتك وأسلوبك.',
      'our_impact_desc': 'منذ تأسيسنا، ساعدنا أكثر من 500,000 طالب على تحقيق أهدافهم التعليمية من خلال كتالوج الدورات الشامل ومجتمعنا الداعم.',
      'our_values': 'قيمنا',
      'community_first': 'المجتمع أولاً',
      'community_first_desc': 'نؤمن بقوة التعلم معًا ودعم بعضنا البعض.',
      'goal_oriented': 'موجه نحو الهدف',
      'goal_oriented_desc': 'تم تصميم كل دورة لمساعدتك على تحقيق أهدافك التعليمية المحددة.',
      'excellence': 'التميز',
      'excellence_desc': 'نحافظ على أعلى المعايير في جودة المحتوى وتجربة التعلم.',
      'passion': 'الشغف',
      'passion_desc': 'نحن متحمسون للتعليم ومساعدة الناس على إطلاق إمكاناتهم.',
      'meet_our_team': 'تعرف على فريقنا',
      'ceo_founder': 'الرئيس التنفيذي والمؤسس',
      'cto': 'المدير التقني',
      'head_of_education': 'رئيس قسم التعليم',
      'lead_developer': 'كبير المطورين',

      // Account Page
      'manage_account_desc': 'إدارة أمان حسابك وتفضيلاتك',
      'security': 'الأمان',
      'change_password': 'تغيير كلمة المرور',
      'current_password': 'كلمة المرور الحالية',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
      'update_password': 'تحديث كلمة المرور',
      'two_factor_auth': 'المصادقة الثنائية',
      'sms_auth': 'المصادقة عبر الرسائل القصيرة',
      'sms_auth_desc': 'استلام الرموز عبر الرسائل القصيرة',
      'notifications': 'الإشعارات',
      'email_notifications': 'إشعارات البريد الإلكتروني',
      'email_notifications_desc': 'استلام الإشعارات عبر البريد الإلكتروني',
      'push_notifications': 'دفع الإشعارات',
      'push_notifications_desc': 'استلام دفع الإشعارات',
      'marketing_emails': 'رسائل التسويق الإلكتروني',
      'marketing_emails_desc': 'استلام المحتوى الترويجي',
      'course_updates': 'تحديثات الدورة',
      'course_updates_desc': 'تحديثات حول الدورات المسجلة الخاصة بك',
      'privacy_settings': 'إعدادات الخصوصية',
      'public_profile': 'الملف الشخصي العام',
      'public_profile_desc': 'اجعل ملفك الشخصي مرئيًا للآخرين',
      'show_learning_progress': 'إظهار تقدم التعلم',
      'show_learning_progress_desc': 'عرض تقدم دورتك بشكل عام',
      'show_certificates': 'إظهار الشهادات',
      'show_certificates_desc': 'عرض الشهادات المكتسبة في الملف الشخصي',
      'billing_payments': 'الفواتير والمدفوعات',
      'payment_methods': 'طرق الدفع',
      'payment_methods_desc': 'إدارة طرق الدفع الخاصة بك',
      'manage': 'إدارة',
      'billing_history': 'سجل الفواتير',
      'billing_history_desc': 'عرض سجل مشترياتك',
      'view_history': 'عرض السجل',
      'danger_zone': 'منطقة الخطر',
      'delete_account': 'حذف الحساب',
      'delete_account_desc': 'حذف حسابك وجميع البيانات بشكل دائم',
      'passwords_do_not_match': 'كلمات المرور غير متطابقة',
      'confirm_delete_account': 'هل أنت متأكد أنك تريد حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.',

      // Contact Page
      'contact_us_desc': 'لديك أسئلة؟ نود أن نسمع منك.',
      'send_us_message': 'أرسل لنا رسالة',
      'name_required': 'الاسم *',
      'email_required': 'البريد الإلكتروني *',
      'subject_required': 'الموضوع *',
      'message_required': 'الرسالة *',
      'sending': 'جارٍ الإرسال...',
      'send_message': 'إرسال الرسالة',
      'get_in_touch': 'ابقى على تواصل',
      'get_in_touch_desc': 'نحن هنا للمساعدة! تواصل معنا عبر أي من القنوات التالية، وسنرد عليك في أقرب وقت ممكن.',
      'support_email_address': 'support@learnhub.com',
      'phone_number': '+1 (555) 123-4567',
      'address_details': '123 شارع التعلم، مدينة التعليم، EC 12345',
      'hours_details': 'الاثنين - الجمعة: 9 صباحًا - 6 مساءً بتوقيت المحيط الهادئ',
      'faq': 'الأسئلة المتكررة',
      'faq_desc': 'راجع قسم الأسئلة الشائعة للحصول على إجابات سريعة للأسئلة الشائعة حول الدورات والمدفوعات والدعم الفني.',
      'message_sent_title': 'تم إرسال الرسالة!',
      'message_sent_desc': 'شكرا لتواصلك معنا. سنرد عليك قريبا.',

      // Course Details Page
      'course_introduction': 'مقدمة الدورة',
      'students_count_details': 'طلاب',
      'created_by': 'أنشأها',
      'last_updated': 'آخر تحديث',
      'what_you_will_learn': 'ماذا ستتعلم',
      'requirements': 'المتطلبات',
      'course_curriculum': 'منهج الدورة',
      'sections': 'أقسام',
      'lectures': 'محاضرات',
      'total_length': 'الطول الإجمالي',
      'preview': 'معاينة',
      'instructor_role': 'مطور ومدرس أول للمكدس الكامل',
      'instructor_rating': 'تقييم المدرب',
      'instructor_bio': 'جون مطور متمرس يتمتع بخبرة تزيد عن 10 سنوات في تطوير الويب. لقد عمل مع كبرى شركات التكنولوجيا وقام بتدريس آلاف الطلاب في جميع أنحاء العالم.',
      'reviews_placeholder': 'سيتم عرض المراجعات هنا',
      'discount_badge': 'خصم 50٪',
      'price_countdown': 'باقي يومان على هذا السعر!',
      'enroll_now': 'سجل الآن',
      'add_to_wishlist': 'أضف إلى قائمة الرغبات',
      'money_back_guarantee': 'ضمان استرداد الأموال لمدة 30 يومًا',
      'full_lifetime_access': 'وصول كامل مدى الحياة',
      'access_on_mobile_tv': 'الوصول على الهاتف المحمول والتلفزيون',
      'certificate_of_completion': 'شهادة إتمام',

      // Course Management Page
      'course_management_title': 'إدارة الدورات',
      'course_management_desc': 'إنشاء وإدارة الدورات الخاصة بك',
      'create_course': 'إنشاء دورة',
      'create_new_course': 'إنشاء دورة جديدة',
      'course_title': 'عنوان الدورة',
      'enter_course_title': 'أدخل عنوان الدورة',
      'description': 'الوصف',
      'course_description': 'وصف الدورة',
      'price_usd': 'السعر (بالدولار الأمريكي)',
      'duration': 'المدة',
      'duration_placeholder': 'على سبيل المثال، 40 ساعة',
      'category': 'الفئة',
      'select_category': 'اختر الفئة',
      'web_development': 'تطوير الويب',
      'data_science': 'علوم البيانات',
      'mobile_development': 'تطوير تطبيقات الجوال',
      'design': 'التصميم',
      'level': 'المستوى',
      'select_level': 'اختر المستوى',
      'beginner': 'مبتدئ',
      'intermediate': 'متوسط',
      'advanced': 'متقدم',
      'price': 'السعر',
      'enrollments': 'التسجيلات',
      'revenue': 'الإيرادات',
      'course_created_toast_title': 'تم إنشاء الدورة',
      'course_created_toast_desc': 'تم إنشاء دورتك الجديدة بنجاح.',
      'course_deleted_toast_title': 'تم حذف الدورة',
      'course_deleted_toast_desc': 'تمت إزالة الدورة من الكتالوج الخاص بك.',

      // Courses Page
      'explore_courses': 'استكشاف الدورات',
      'search_courses_instructors': 'البحث عن الدورات أو المدربين...',
      'filters': 'المرشحات',
      'categories': 'الفئات',
      'free': 'مجاني',
      'paid': 'مدفوع',
      'clear_filters': 'مسح المرشحات',
      'courses_found': 'دورات موجودة',
      'no_courses_found': 'لم يتم العثور على دورات',
      'try_adjusting_filters': 'حاول تعديل معايير البحث أو التصفية',
      'marketing': 'التسويق',
      'business': 'الأعمال',

      // Dashboard Page
      'welcome_back': 'مرحبًا بعودتك يا {userName}!',
      'learning_journey_prompt': 'هل أنت مستعد لمواصلة رحلتك التعليمية؟',
      'your_progress': 'تقدمك',
      'courses_enrolled_dashboard': 'الدورات المسجلة',
      'average_progress': 'متوسط التقدم',
      'total_learning_time': 'إجمالي وقت التعلم',
      'my_courses': 'دوراتي',
      'by_instructor': 'بواسطة {instructor}',
      'progress': 'التقدم',
      'lessons_count': 'دروس',
      'next_lesson_prompt': 'التالي: {nextLesson}',
      'continue_learning': 'متابعة',
      'browse_courses': 'تصفح الدورات',
      'edit_profile': 'تعديل الملف الشخصي',
      'achievements': 'الإنجازات',
      'first_course_completed_achievement': 'إكمال الدورة الأولى',
      'week_streak_achievement': 'سلسلة أسبوعية',
      'fast_learner_achievement': 'متعلم سريع',
      'earned_badge': 'مكتسب',

      // Login Page
      'login_successful_modal_title': 'تم تسجيل الدخول بنجاح',
      'login_failed_modal_title': 'فشل تسجيل الدخول',
      'login_successful_modal_desc': 'مرحبًا بعودتك! لقد تم تسجيل دخولك بنجاح.',
      'login_failed_modal_desc': 'بريد إلكتروني أو كلمة مرور غير صالحة. حاول مرة اخرى.',

      // Not Found Page
      'not_found_title': '404',
      'not_found_message': 'عفوًا! الصفحة غير موجودة',
      'return_to_home': 'العودة إلى الصفحة الرئيسية',

      // Payment Page
      'complete_your_purchase': 'أكمل عملية الشراء',
      'secure_checkout_desc': 'دفع آمن مدعوم بتشفير قياسي في الصناعة',
      'payment_information': 'معلومات الدفع',
      'payment_method': 'طريقة الدفع',
      'credit_debit_card': 'بطاقة الائتمان/الخصم',
      'paypal_coming_soon': 'PayPal (قريبًا)',
      'card_number': 'رقم البطاقة',
      'expiry_date': 'تاريخ انتهاء الصلاحية',
      'cvv': 'CVV',
      'cardholder_name': 'اسم صاحب البطاقة',
      'billing_address': 'عنوان الفواتير',
      'first_name': 'الاسم الأول',
      'last_name': 'اسم العائلة',
      'city': 'المدينة',
      'state': 'الولاية',
      'zip_code': 'الرمز البريدي',
      'processing': 'جارٍ المعالجة...',
      'pay_amount': 'ادفع ${course.price}',
      'order_summary': 'ملخص الطلب',
      'course_price': 'سعر الدورة:',
      'discount_label': 'الخصم:',
      'total_label': 'المجموع:',
      'secure_encryption_desc': 'تشفير SSL آمن 256 بت',

      // Payment Analytics Page
      'payment_analytics_title': 'تحليلات الدفع',
      'payment_analytics_desc': 'تتبع إيراداتك وأداء الدفع',
      'filter_button': 'تصفية',
      'export_button': 'تصدير',
      'last_30_days': 'آخر 30 يومًا',
      'monthly_growth': 'النمو الشهري',
      'compared_to_last_month': 'مقارنة بالشهر الماضي',
      'total_transactions': 'إجمالي المعاملات',
      'this_month': 'هذا الشهر',
      'average_order_value': 'متوسط قيمة الطلب',
      'per_transaction': 'لكل معاملة',
      'recent_payments': 'المدفوعات الأخيرة',
      'subscriptions': 'الاشتراكات',
      'active_subscriptions': 'الاشتراكات النشطة',
      'next_billing_date': 'الفواتير التالية: {nextBilling}',
      'amount_per_month': '${amount}/شهر',

      // Payment Success Page
      'payment_successful_title': 'تم الدفع بنجاح!',
      'payment_successful_desc': 'شكرا لك على شرائك. لديك الآن حق الوصول إلى دورتك.',
      'course_enrolled_label': 'الدورة المسجلة:',
      'go_to_dashboard_button': 'اذهب إلى لوحة التحكم',
      'browse_more_courses_button': 'تصفح المزيد من الدورات',
      'confirmation_email_sent': 'تم إرسال رسالة تأكيد بالبريد الإلكتروني إلى عنوان بريدك الإلكتروني المسجل.',

      // Profile Page
      'manage_profile_desc': 'إدارة معلوماتك الشخصية وملفك الشخصي العام',
      'profile_picture': 'صورة الملف الشخصي',
      'change_picture': 'تغيير الصورة',
      'personal_information': 'المعلومات الشخصية',
      'edit_button': 'تعديل',
      'bio': 'السيرة الذاتية',
      'website': 'موقع الكتروني',
      'linkedin': 'لينكد إن',
      'twitter': 'تويتر',
      'save_changes_button': 'حفظ التغييرات',

      // Promo Code Management Page
      'promo_code_management_title': 'إدارة أكواد الخصم',
      'promo_code_management_desc': 'إنشاء وإدارة أكواد الخصم لدوراتك',
      'create_promo_code_button': 'إنشاء كود خصم',
      'create_new_promo_code_title': 'إنشاء كود خصم جديد',
      'promo_code_label': 'كود الخصم',
      'enter_or_generate_code': 'أدخل الكود أو قم بإنشائه',
      'generate_button': 'إنشاء',
      'promo_code_desc_label': 'وصف كود الخصم',
      'discount_type_label': 'نوع الخصم',
      'percentage_option': 'نسبة مئوية',
      'fixed_amount_option': 'مبلغ ثابت',
      'percentage_input_label': 'النسبة المئوية (%)',
      'amount_input_label': 'المبلغ (بالدولار الأمريكي)',
      'usage_limit_label': 'حد الاستخدام',
      'applicable_courses_label': 'الدورات القابلة للتطبيق',
      'all_courses_option': 'جميع الدورات',
      'discount_column': 'الخصم',
      'usage_column': 'الاستخدام',
      'expires_column': 'تنتهي صلاحيته',
      'all_option': 'الكل',
      'promo_code_created_toast_title': 'تم إنشاء كود الخصم',
      'promo_code_created_toast_desc': 'تم إنشاء كود الخصم الجديد الخاص بك بنجاح.',
      'promo_code_deleted_toast_title': 'تم حذف كود الخصم',
      'promo_code_deleted_toast_desc': 'تمت إزالة كود الخصم.',
      'code_copied_toast_title': 'تم نسخ الكود',
      'code_copied_toast_desc': 'تم نسخ كود الخصم "{code}" إلى الحافظة.',

      // Quiz Management Page
      'quiz_management_title': 'إدارة الاختبارات',
      'quiz_management_desc': 'إنشاء وإدارة اختبارات الدورة',
      'create_quiz_button': 'إنشاء اختبار',
      'create_new_quiz_title': 'إنشاء اختبار جديد',
      'quiz_title_label': 'عنوان الاختبار',
      'enter_quiz_title': 'أدخل عنوان الاختبار',
      'duration_minutes_label': 'المدة (بالدقائق)',
      'quiz_desc_label': 'وصف الاختبار',
      'associated_lesson_label': 'الدرس المرتبط',
      'lesson_name_placeholder': 'اسم الدرس',
      'questions_label': 'الأسئلة',
      'add_question_button': 'إضافة سؤال',
      'question_label': 'السؤال {index + 1}',
      'enter_question_placeholder': 'أدخل سؤالك',
      'option_label': 'الخيار {optionIndex + 1}',
      'correct_answer_label': 'الإجابة الصحيحة',
      'option_1': 'الخيار 1',
      'option_2': 'الخيار 2',
      'option_3': 'الخيار 3',
      'option_4': 'الخيار 4',
      'lesson_prefix': 'الدرس: {lesson}',
      'attempts_label': 'المحاولات',
      'avg_score_label': 'متوسط الدرجات',
      'quiz_created_toast_title': 'تم إنشاء الاختبار',
      'quiz_created_toast_desc': 'تم إنشاء اختبارك الجديد بنجاح.',
      'quiz_deleted_toast_title': 'تم حذف الاختبار',
      'quiz_deleted_toast_desc': 'تمت إزالة الاختبار.',

      // Signup Page
      'create_account_title': 'إنشاء حساب',
      'join_community_desc': 'انضم إلى مجتمعنا التعليمي',
      'signup_with_gmail_button': 'التسجيل باستخدام Gmail',
      'or_continue_with': 'أو المتابعة باستخدام',
      'i_want_to_label': 'أريد أن',
      'learn_as_student_option': 'أتعلم كطالب',
      'teach_as_instructor_option': 'أدرس كمدرب',
      'password_label': 'كلمة المرور',
      'creating_account_button': 'جارٍ إنشاء الحساب...',
      'already_have_account_prompt': 'هل لديك حساب بالفعل؟ ',
      'sign_in_link': 'تسجيل الدخول',

      // Teacher Dashboard Page
      'instructor_dashboard_title': 'لوحة تحكم المدرب',
      'instructor_dashboard_desc': 'إدارة الدورات الخاصة بك وتتبع الأداء',
      'quizzes_nav': 'الاختبارات',
      'manage_quizzes_nav_desc': 'إنشاء وإدارة الاختبارات',
      'track_payments_nav_desc': 'تتبع المدفوعات والإيرادات',
      'promo_codes_nav': 'أكواد الخصم',
      'manage_promo_codes_nav_desc': 'إدارة أكواد الخصم',
      'total_courses_stats': 'إجمالي الدورات',
      'avg_rating_stats': 'متوسط التقييم',
      'payments_tab': 'المدفوعات',
      'promos_tab': 'أكواد الخصم',
      'add_course_button': 'إضافة دورة',
      'course_title_required_label': 'عنوان الدورة *',
      'price_required_label': 'السعر *',
      'programming_option': 'البرمجة',
      'students_stats_prefix': 'الطلاب: {students}',
      'revenue_stats_prefix': 'الإيرادات: ${revenue}',
      'price_stats_prefix': 'السعر: ${price}',
      'rating_stats_prefix': 'التقييم: {rating}/5',
      'no_ratings_label': 'لا توجد تقييمات',
      'view_button': 'عرض',
      'remove_button': 'إزالة',
      'payment_history_title': 'سجل المدفوعات',
      'student_column': 'الطالب',
      'course_column': 'الدورة',
      'amount_column': 'المبلغ',
      'date_column': 'التاريخ',
      'status_column': 'الحالة',
      'create_promo_button': 'إنشاء خصم',
      'promo_code_required_label': 'كود الخصم *',
      'discount_required_label': 'الخصم *',
      'select_type_placeholder': 'اختر النوع',
      'percentage_discount_option': 'نسبة مئوية (%)',
      'fixed_amount_discount_option': 'مبلغ ثابت (بالدولار الأمريكي)',
      'max_uses_label': 'أقصى استخدام',
      'code_column': 'الكود',
      'discount_value_suffix': '{discount}{type} خصم',
      'error_toast_title': 'خطأ',
      'fill_required_fields_toast_desc': 'يرجى ملء جميع الحقول المطلوبة',
      'success_toast_title': 'نجاح',
      'course_created_successfully_toast_desc': 'تم إنشاء الدورة بنجاح',
      'course_removed_successfully_toast_desc': 'تمت إزالة الدورة بنجاح',
      'promo_code_created_successfully_toast_desc': 'تم إنشاء كود الخصم بنجاح',

      // Course Card Component
      'view_details_button': 'عرض التفاصيل',

      // Courses Preview Component
      'featured_courses_title': 'الدورات المميزة',
      'featured_courses_desc': 'اكتشف دوراتنا الأكثر شيوعًا وابدأ رحلتك التعليمية اليوم',
      'view_all_courses_button': 'عرض جميع الدورات',

      // Feature Section Component
      'why_choose_platform_title': 'لماذا تختار منصتنا؟',
      'why_choose_platform_desc': 'اكتشف الميزات التي تجعل التعلم فعالاً وجذابًا ومتاحًا للجميع.',
      'expert_instructors_feature_title': 'مدربون خبراء',
      'expert_instructors_feature_desc': 'تعلم من محترفي الصناعة والخبراء المعتمدين الذين يجلبون خبرة العالم الحقيقي إلى كل درس.',
      'flexible_learning_feature_title': 'تعلم مرن',
      'flexible_learning_feature_desc': 'ادرس بالسرعة التي تناسبك مع إمكانية الوصول إلى مواد الدورة على مدار الساعة طوال أيام الأسبوع. مثالي للجداول الزمنية المزدحمة وأنماط التعلم المختلفة.',
      'interactive_content_feature_title': 'محتوى تفاعلي',
      'interactive_content_feature_desc': 'شارك في المشاريع العملية والاختبارات والمناقشات المجتمعية لتعزيز تجربة التعلم الخاصة بك.',
      'comprehensive_curriculum_feature_title': 'منهج شامل',
      'comprehensive_curriculum_feature_desc': 'يمكنك الوصول إلى مسارات تعلم منظمة مصممة لتأخذك من مبتدئ إلى خبير في المجال الذي اخترته.',
      'certificates_recognition_feature_title': 'الشهادات والتقدير',
      'certificates_recognition_feature_desc': 'احصل على شهادات معتمدة عند الانتهاء لعرض مهاراتك لأصحاب العمل والتقدم في حياتك المهنية.',
      'support_24_7_feature_title': 'دعم على مدار الساعة',
      'support_24_7_feature_desc': 'احصل على المساعدة متى احتجت إليها من خلال فريق الدعم المخصص ومنتديات المجتمع النشطة.',

      // Hero Section Component
      'hero_title': 'تعلم أي شيء، في أي وقت',
      'hero_subtitle': 'تبدأ رحلتك إلى المعرفة من هنا. يمكنك الوصول إلى آلاف الدورات التدريبية من مدربين خبراء والتعلم بالسرعة التي تناسبك.',
      'watch_demo_button': 'مشاهدة العرض التوضيحي',
      'courses_available_stats': 'الدورات المتاحة',
      'students_enrolled_stats': 'الطلاب المسجلون',
      'expert_instructors_stats': 'مدربون خبراء',
      'promo_video_title': 'فيديو ترويجي لمنصة التعلم',

      // Login Form Component
      'welcome_back_title': 'مرحبًا بعودتك',
      'sign_in_to_account_desc': 'تسجيل الدخول إلى حسابك',
      'continue_with_gmail_button': 'المتابعة باستخدام Gmail',
      'enter_your_email_placeholder': 'أدخل بريدك الإلكتروني',
      'enter_your_password_placeholder': 'أدخل كلمة المرور الخاصة بك',
      'forgot_password_link': 'هل نسيت كلمة المرور؟',
      'signing_in_button': 'جارٍ تسجيل الدخول...',
      'sign_in_button': 'تسجيل الدخول',
      'dont_have_account_prompt': 'ليس لديك حساب؟ ',
      'sign_up_link': 'إنشاء حساب',

      // Modal Component
      'ok_button': 'موافق',

      // Video Player Component
      'sample_video_badge': 'عينة',

      // Admin Analytics Dashboard Component
      'total_users_stats': 'إجمالي المستخدمين',
      'plus_15_percent_from_last_month': '+15٪ من الشهر الماضي',
      'course_completions_stats': 'إكمالات الدورة',
      'plus_8_percent_from_last_month': '+8٪ من الشهر الماضي',
      'avg_session_time_stats': 'متوسط وقت الجلسة',
      'plus_5_percent_from_last_month': '+5٪ من الشهر الماضي',
      'platform_rating_stats': 'تقييم المنصة',
      'plus_0_2_from_last_month': '+0.2 من الشهر الماضي',
      'user_growth_chart_title': 'نمو المستخدمين',
      'revenue_trend_chart_title': 'اتجاه الإيرادات',
      'course_completion_status_chart_title': 'حالة إكمال الدورة',
      'top_performing_courses_chart_title': 'الدورات الأفضل أداءً',
      'platform_performance_summary_title': 'ملخص أداء المنصة',
      'student_engagement_section_title': 'مشاركة الطلاب',
      'daily_active_users_label': 'المستخدمون النشطون يوميًا:',
      'weekly_active_users_label': 'المستخدمون النشطون أسبوعيًا:',
      'monthly_active_users_label': 'المستخدمون النشطون شهريًا:',
      'teacher_performance_section_title': 'أداء المعلمين',
      'avg_course_rating_label': 'متوسط تقييم الدورة:',
      'course_completion_rate_label': 'معدل إكمال الدورة:',
      'student_satisfaction_label': 'رضا الطلاب:',
      'revenue_metrics_section_title': 'مقاييس الإيرادات',
      'monthly_revenue_label': 'الإيرادات الشهرية:',
      'avg_course_price_label': 'متوسط سعر الدورة:',
      'revenue_growth_label': 'نمو الإيرادات:',
      'plus_23_percent': '+23٪',

      // Admin Platform Settings Component
      'platform_settings_title': 'إعدادات المنصة',
      'general_settings_section_title': 'الإعدادات العامة',
      'platform_name_label': 'اسم المنصة',
      'support_email_label': 'بريد الدعم الإلكتروني',
      'welcome_message_label': 'رسالة ترحيب',
      'user_registration_section_title': 'تسجيل المستخدمين',
      'enable_user_registration_label': 'تمكين تسجيل المستخدمين',
      'enable_user_registration_desc': 'السماح للمستخدمين الجدد بالتسجيل في المنصة',
      'require_email_verification_label': 'طلب التحقق من البريد الإلكتروني',
      'require_email_verification_desc': 'يجب على المستخدمين التحقق من بريدهم الإلكتروني قبل الوصول إلى المنصة',
      'allow_guest_access_label': 'السماح بوصول الضيوف',
      'allow_guest_access_desc': 'السماح للمستخدمين بتصفح الدورات دون تسجيل',
      'system_settings_section_title': 'إعدادات النظام',
      'max_file_upload_size_label': 'الحد الأقصى لحجم تحميل الملف (ميجابايت)',
      'session_timeout_label': 'مهلة الجلسة (بالدقائق)',
      'maintenance_mode_label': 'وضع الصيانة',
      'maintenance_mode_desc': 'تمكين وضع الصيانة لمنع وصول المستخدمين',
      'max_courses_per_teacher_label': 'الحد الأقصى للدورات لكل معلم',
      'course_approval_required_label': 'مطلوب موافقة على الدورة',
      'course_approval_required_desc': 'تتطلب الدورات الجديدة موافقة المسؤول قبل النشر',
      'save_all_settings_button': 'حفظ جميع الإعدادات',
      'system_status_title': 'حالة النظام',
      'online_status': 'متصل',
      'server_status_label': 'حالة الخادم',
      'uptime_label': 'وقت التشغيل',
      'avg_response_time_label': 'متوسط وقت الاستجابة',

      // Admin Revenue Control Component
      'platform_revenue_stats': 'إيرادات المنصة',
      'percent_of_total_label': '٪ من الإجمالي',
      'teacher_revenue_stats': 'إيرادات المعلمين',
      'global_revenue_settings_title': 'إعدادات الإيرادات العالمية',
      'platform_fee_percentage_label': 'رسوم المنصة (٪)',
      'platform_fee_percentage_desc': 'نسبة إيرادات الدورة التي تذهب إلى المنصة',
      'teacher_share_percentage_label': 'حصة المعلم (٪)',
      'teacher_share_percentage_desc': 'نسبة إيرادات الدورة التي تذهب إلى المعلمين',
      'auto_approve_course_pricing_label': 'الموافقة التلقائية على أسعار الدورات',
      'auto_approve_course_pricing_desc': 'الموافقة تلقائيًا على تغييرات أسعار الدورات التي يجريها المعلمون',
      'update_global_settings_button': 'تحديث الإعدادات العالمية',
      'course_revenue_management_title': 'إدارة إيرادات الدورات',
      'teacher_share_column': 'حصة المعلم',
      'platform_fee_column': 'رسوم المنصة',
      'pricing_insights_title': 'رؤى التسعير',
      'avg_course_price_stats': 'متوسط سعر الدورة:',
      'highest_priced_course_stats': 'أعلى سعر للدورة:',
      'lowest_priced_course_stats': 'أقل سعر للدورة:',
      'courses_pending_approval_stats': 'الدورات التي تنتظر الموافقة:',
      'revenue_distribution_title': 'توزيع الإيرادات',
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};
